version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/ICTA/Works/data/
  nginx:
    image: railway_system/nginx
    ports:
      - "81:80"
  client_service:
    image: railway_system/railway-service
    ports: 
      - "8082:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/inventory
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none