version: "3.0"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      - POSTGRESQL_PASSWORD=bitnami
      - DATABASE_PORT_NUMBER=5432
    ports:
      - '5432:5432'
    volumes:
        - 'postgresql_master_data:/bitnami/postgresql'
  phppgadmin:
    image: docker.io/bitnami/phppgadmin:7
    environment:
      - DATABASE_HOST=postgresql
    ports:
      - '82:8080'
      - '443:8443'
    depends_on:
      - postgresql
  nginx:
    image: railway-inventory-system/client
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  backend:
    image: railway-inventory-system/service
    ports: 
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=bitnami
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  postgresql_master_data: