version: "3.0"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes: 
      #- ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  nginx:
    image: railway_system/nginx:latest
    ports:
      - "80:80"
    volumes:
      - E:/Works/railway-inventory-system/nginx/nginx.conf:/etc/nginx/nginx.conf
  client:
    image: railway_system/railway-service
    ports: 
      - "8082:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none